# Generated by Django 4.1.4 on 2022-12-29 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.EmailField(blank=True, max_length=20, null=True)),
                ('Username', models.CharField(blank=True, max_length=20, null=True)),
                ('Password', models.CharField(blank=True, max_length=20, null=True)),
                ('Gender', models.CharField(blank=True, max_length=6, null=True)),
                ('Address', models.TextField(blank=True, max_length=20, null=True)),
                ('Designation', models.CharField(blank=True, max_length=30, null=True)),
                ('Number', models.CharField(blank=True, max_length=10, null=True)),
                ('Picture', models.FileField(blank=True, default='User.jpg', null=True, upload_to='Employees')),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskName', models.CharField(blank=True, max_length=20, null=True)),
                ('Taskdesc', models.TextField(blank=True, max_length=130, null=True)),
                ('startdate', models.DateField()),
                ('duedate', models.DateField()),
                ('TaskStatus', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ManyToManyField(to='employees.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProName', models.CharField(blank=True, max_length=20, null=True)),
                ('Prodesc', models.TextField(blank=True, max_length=130, null=True)),
                ('startdate', models.DateField()),
                ('duedate', models.DateField()),
                ('ProStatus', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.profile')),
            ],
        ),
    ]
