# Generated by Django 4.1.4 on 2023-01-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgdate', models.DateTimeField(auto_created=True)),
                ('Message', models.TextField(blank=True, max_length=200, null=True)),
                ('user', models.ManyToManyField(to='employees.profile')),
            ],
        ),
    ]
