# Generated by Django 4.1.4 on 2023-01-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='msgdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
