# Generated by Django 4.1.4 on 2023-01-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_rename_user_notification_to_notification_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='Assigned_to',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='Assigned_to',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='From',
        ),
    ]
