# Generated by Django 4.1.4 on 2023-01-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_rename_profile_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='msgdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date and Time'),
        ),
    ]
