# Generated by Django 4.1.4 on 2023-01-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_remove_project_prostatus_remove_task_taskstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='upload_file',
            field=models.FileField(blank=True, max_length=130, null=True, upload_to='Project_file', verbose_name='Project file'),
        ),
        migrations.AlterField(
            model_name='task',
            name='upload_file',
            field=models.FileField(blank=True, max_length=130, null=True, upload_to='Task_file', verbose_name='Task file'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Picture',
            field=models.FileField(blank=True, default='User.jpg', null=True, upload_to='Profile_picture'),
        ),
    ]
