# Generated by Django 4.1.4 on 2023-01-22 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_project_status_alter_task_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='upload_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='upload_file',
            new_name='file',
        ),
    ]
