# Generated by Django 4.1.4 on 2023-01-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_rename_upload_file_project_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, default=None, max_length=130, null=True, upload_to='Project_file', verbose_name='Project file'),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, default=None, max_length=130, null=True, upload_to='Task_file', verbose_name='Task file'),
        ),
    ]
