# Generated by Django 4.1.4 on 2023-01-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_alter_project_file_alter_task_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, max_length=130, null=True, upload_to='Project_file', verbose_name='Project file'),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, max_length=130, null=True, upload_to='Task_file', verbose_name='Task file'),
        ),
    ]
