# Generated by Django 4.1.4 on 2023-01-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_alter_project_file_alter_task_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Prodesc',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Project_file', verbose_name='Project file'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Taskdesc',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Task Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Task_file', verbose_name='Task file'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Address',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
