# Generated by Django 4.1.4 on 2023-01-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_alter_project_prodesc_alter_project_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='Message',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Message Body'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='Title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Message Title'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6, null=True),
        ),
    ]
