# Generated by Django 4.1.4 on 2023-01-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_alter_notification_message_alter_notification_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
    ]
