# Generated by Django 4.1.4 on 2023-01-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_alter_userdetail_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetail',
            new_name='UserEmployee',
        ),
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
