# Generated by Django 4.1.4 on 2023-01-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_rename_userdetail_useremployee_notification_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='msgdate',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='read',
            new_name='Read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='Title',
        ),
        migrations.AddField(
            model_name='notification',
            name='Subject',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='Message',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
