# Generated by Django 4.1.4 on 2023-01-28 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_rename_msgdate_notification_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='From',
        ),
    ]
