# Generated by Django 4.1.4 on 2023-01-28 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0020_remove_notification_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='From',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='To',
        ),
        migrations.AddField(
            model_name='notification',
            name='To',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.useremployee'),
        ),
    ]
