# Generated by Django 4.1.4 on 2023-02-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_profile_alter_notification_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Progress', 'Progress')], default='Progress', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='Status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Progress', 'Progress')], default='Progress', max_length=10, null=True),
        ),
    ]
