# Generated by Django 4.1.4 on 2023-02-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0024_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='Read',
            field=models.BooleanField(default=False),
        ),
    ]
